#!/bin/bash

source ~/.bash_profile
source ./lib/utils

e_header "Installing Node & NPM (Node Package Manager)..."
  brew install node

 e_header "Installing Grunt..."
  npm install -g grunt-cli

e_header "Installing Coffeescript..."
  npm install -g coffee-script

e_header "Installing JSHint to validate Javascript code..."
  npm install -g jshint

e_header "Installing Uglify for minifying Javascript code..."
  npm install -g uglify-js

source ~/.bash_profile
